#!/usr/bin/env python3
"""Concatenate every migration plus the seed into supabase/setup.sql.

setup.sql is the one-paste installer in SETUP.md. It used to be maintained by
hand, which is why it drifted five migrations behind. Regenerate it instead:

    bun run db:setup
"""
import pathlib

ROOT = pathlib.Path(__file__).parent
MIGRATIONS = sorted((ROOT / "migrations").glob("*.sql"))
SEED = ROOT / "seed.sql"

HEADER = """\
-- ============================================================================
-- Rentio — complete setup, in one script.
--
-- GENERATED by supabase/build-setup.py. Do not edit; edit the migrations in
-- supabase/migrations/ or supabase/seed.sql and run `bun run db:setup`.
--
-- Paste the whole file into Supabase -> SQL Editor -> New query -> Run.
-- Order matters: schema, then RLS, then the views, then the Texas compliance
-- migrations, then demo data.
--
-- The LAST section is DEMO DATA and begins with TRUNCATE. Delete it before
-- running this against anything but a demo or staging project.
--
-- DEMO LOGINS ARE NOT CREATED HERE. Inserting into auth.users by hand breaks
-- sign-in for the whole project, so run this afterwards instead:
--
--     bun run db:demo-logins
--
-- Then verify with supabase/tests/rls_test.sql.
-- ============================================================================
"""


def section(title: str, body: str) -> str:
    bar = "=" * 76
    return f"\n\n-- {bar}\n-- {title}\n-- {bar}\n{body.rstrip()}\n"


parts = [HEADER]
for index, path in enumerate(MIGRATIONS, start=1):
    parts.append(
        section(f"{index}/{len(MIGRATIONS) + 1}  {path.stem}", path.read_text())
    )
parts.append(
    section(f"{len(MIGRATIONS) + 1}/{len(MIGRATIONS) + 1}  DEMO DATA", SEED.read_text())
)

(ROOT / "setup.sql").write_text("".join(parts))
print(f"setup.sql: {len(MIGRATIONS)} migrations + seed")
