-- ============================================================================
-- Rentio — complete setup, in one script.
--
-- GENERATED by supabase/build-setup.py. Do not edit; edit the migrations in
-- supabase/migrations/ or supabase/seed.sql and run `bun run db:setup`.
--
-- Paste the whole file into Supabase -> SQL Editor -> New query -> Run.
-- Order matters: schema, then RLS, then the views, then the Texas compliance
-- migrations, then demo data.
--
-- The LAST section is DEMO DATA and begins with TRUNCATE. Delete it before
-- running this against anything but a demo or staging project.
--
-- DEMO LOGINS ARE NOT CREATED HERE. Inserting into auth.users by hand breaks
-- sign-in for the whole project, so run this afterwards instead:
--
--     bun run db:demo-logins
--
-- Then verify with supabase/tests/rls_test.sql.
-- ============================================================================


-- ============================================================================
-- 1/13  20260919000100_schema
-- ============================================================================
-- Rentio — core schema
-- All money is numeric(12,2). Never float.

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------- enums

create type user_role         as enum ('admin', 'manager', 'tenant');
create type unit_status       as enum ('vacante', 'ocupada', 'mantenimiento', 'reservada');
create type lease_status      as enum ('borrador', 'activo', 'por_vencer', 'terminado', 'rescindido');
create type lease_tenant_role as enum ('primary', 'co_tenant', 'guarantor');
create type invoice_status    as enum ('borrador', 'enviado', 'pagado_parcial', 'pagado', 'vencido', 'cancelado');
create type line_category     as enum ('renta', 'estacionamiento', 'servicios', 'cuota_mantenimiento', 'recargo', 'otro');
create type payment_method    as enum ('spei', 'efectivo', 'deposito', 'oxxo', 'cheque', 'tarjeta');
create type payment_status    as enum ('pendiente', 'confirmado', 'cancelado');
create type utility_type      as enum ('agua', 'luz', 'gas', 'cuota_mantenimiento', 'otro');
create type utility_status    as enum ('pendiente', 'facturado');
create type wo_source         as enum ('portal', 'whatsapp', 'telefono', 'personal');
create type wo_category       as enum ('plomeria', 'electricidad', 'cerrajeria', 'electrodomesticos', 'limpieza', 'otro');
create type wo_priority       as enum ('baja', 'media', 'alta', 'urgente');
create type wo_status         as enum ('nueva', 'asignada', 'en_progreso', 'esperando_refacciones', 'resuelta', 'cerrada');

-- ------------------------------------------------------- updated_at trigger

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- ---------------------------------------------------------------- tables

create table public.properties (
  id           uuid primary key default gen_random_uuid(),
  name         text not null,
  street       text,
  colonia      text,
  city         text,
  state        text,
  postal_code  text,
  notes        text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz
);

create table public.units (
  id           uuid primary key default gen_random_uuid(),
  property_id  uuid not null references public.properties (id) on delete cascade,
  unit_number  text not null,
  floor        int,
  bedrooms     int,
  bathrooms    numeric(3,1),
  sqm          numeric(8,2),
  base_rent    numeric(12,2) not null default 0,
  status       unit_status not null default 'vacante',
  created_at   timestamptz not null default now(),
  updated_at   timestamptz,
  unique (property_id, unit_number)
);

create table public.tenants (
  id                       uuid primary key default gen_random_uuid(),
  full_name                text not null,
  email                    text,
  phone                    text,
  rfc                      text,
  emergency_contact_name   text,
  emergency_contact_phone  text,
  notes                    text,
  created_at               timestamptz not null default now(),
  updated_at               timestamptz
);

create table public.profiles (
  id          uuid primary key references auth.users (id) on delete cascade,
  full_name   text,
  phone       text,
  role        user_role not null default 'tenant',
  locale      text not null default 'es-MX',
  tenant_id   uuid references public.tenants (id) on delete set null,
  avatar_url  text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz
);

create table public.leases (
  id                 uuid primary key default gen_random_uuid(),
  unit_id            uuid not null references public.units (id) on delete restrict,
  start_date         date not null,
  end_date           date not null,
  rent_amount        numeric(12,2) not null,
  rent_due_day       int not null default 1 check (rent_due_day between 1 and 31),
  grace_days         int not null default 5,
  late_fee_amount    numeric(12,2) not null default 0,
  deposit_amount     numeric(12,2) not null default 0,
  deposit_status     text not null default 'retenido',
  deposit_refunded   numeric(12,2),
  deposit_retained   numeric(12,2),
  deposit_notes      text,
  status             lease_status not null default 'borrador',
  contract_url       text,
  move_out_date      date,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz
);

create table public.parking_spaces (
  id           uuid primary key default gen_random_uuid(),
  property_id  uuid not null references public.properties (id) on delete cascade,
  label        text not null,
  type         text not null default 'techado',
  monthly_fee  numeric(12,2) not null default 0,
  status       text not null default 'disponible',
  lease_id     uuid references public.leases (id) on delete set null,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz,
  unique (property_id, label)
);

create table public.lease_tenants (
  id         uuid primary key default gen_random_uuid(),
  lease_id   uuid not null references public.leases (id) on delete cascade,
  tenant_id  uuid not null references public.tenants (id) on delete cascade,
  role       lease_tenant_role not null default 'primary',
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  unique (lease_id, tenant_id)
);

create table public.invoices (
  id             uuid primary key default gen_random_uuid(),
  lease_id       uuid not null references public.leases (id) on delete restrict,
  period_month   date not null,
  invoice_number text unique,
  issue_date     date not null default current_date,
  due_date       date not null,
  status         invoice_status not null default 'borrador',
  total          numeric(12,2) not null default 0,
  cancel_reason  text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz,
  -- the backstop against double-generating a month
  unique (lease_id, period_month)
);

create table public.invoice_lines (
  id          uuid primary key default gen_random_uuid(),
  invoice_id  uuid not null references public.invoices (id) on delete cascade,
  description text not null,
  category    line_category not null default 'otro',
  quantity    numeric not null default 1,
  amount      numeric(12,2) not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz
);

create table public.payments (
  id                  uuid primary key default gen_random_uuid(),
  lease_id            uuid not null references public.leases (id) on delete restrict,
  amount              numeric(12,2) not null check (amount > 0),
  paid_at             date not null default current_date,
  method              payment_method not null default 'spei',
  reference           text,
  status              payment_status not null default 'pendiente',
  receipt_url         text,
  reported_by_tenant  boolean not null default false,
  recorded_by         uuid references public.profiles (id) on delete set null,
  confirmed_by        uuid references public.profiles (id) on delete set null,
  confirmed_at        timestamptz,
  void_reason         text,
  notes               text,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz
);

create table public.payment_allocations (
  id          uuid primary key default gen_random_uuid(),
  payment_id  uuid not null references public.payments (id) on delete cascade,
  invoice_id  uuid not null references public.invoices (id) on delete cascade,
  amount      numeric(12,2) not null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz
);

create table public.utility_charges (
  id            uuid primary key default gen_random_uuid(),
  unit_id       uuid not null references public.units (id) on delete cascade,
  lease_id      uuid references public.leases (id) on delete set null,
  type          utility_type not null default 'otro',
  period_month  date not null,
  amount        numeric(12,2) not null default 0,
  status        utility_status not null default 'pendiente',
  invoice_id    uuid references public.invoices (id) on delete set null,
  notes         text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz,
  -- "Captura masiva" skips units that already have this type for this month
  unique (unit_id, type, period_month)
);

create table public.work_orders (
  id                  uuid primary key default gen_random_uuid(),
  unit_id             uuid not null references public.units (id) on delete cascade,
  lease_id            uuid references public.leases (id) on delete set null,
  reported_by_tenant  uuid references public.tenants (id) on delete set null,
  source              wo_source not null default 'personal',
  category            wo_category not null default 'otro',
  priority            wo_priority not null default 'media',
  folio               text unique,
  title               text not null,
  description         text,
  status              wo_status not null default 'nueva',
  vendor_name         text,
  vendor_phone        text,
  cost                numeric(12,2),
  resolved_at         timestamptz,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz
);

create table public.work_order_notes (
  id             uuid primary key default gen_random_uuid(),
  work_order_id  uuid not null references public.work_orders (id) on delete cascade,
  author_id      uuid references public.profiles (id) on delete set null,
  body           text not null,
  is_internal    boolean not null default true,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz
);

create table public.work_order_photos (
  id             uuid primary key default gen_random_uuid(),
  work_order_id  uuid not null references public.work_orders (id) on delete cascade,
  url            text not null,
  uploaded_by    uuid references public.profiles (id) on delete set null,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz
);

create table public.documents (
  id          uuid primary key default gen_random_uuid(),
  owner_type  text not null,
  owner_id    uuid not null,
  name        text not null,
  url         text not null,
  uploaded_by uuid references public.profiles (id) on delete set null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz
);

create table public.activity_log (
  id          uuid primary key default gen_random_uuid(),
  actor_id    uuid references public.profiles (id) on delete set null,
  entity_type text not null,
  entity_id   uuid,
  action      text not null,
  meta        jsonb not null default '{}'::jsonb,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz
);

create table public.settings (
  id                  uuid primary key default gen_random_uuid(),
  singleton           boolean not null default true unique check (singleton),
  company_name        text not null default 'Rentio',
  logo_url            text,
  bank_name           text,
  clabe               text,
  account_holder      text,
  invoice_prefix      text not null default 'REC',
  default_late_fee    numeric(12,2) not null default 0,
  default_grace_days  int not null default 5,
  street              text,
  colonia             text,
  city                text,
  state               text,
  postal_code         text,
  phone               text,
  email               text,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz
);

-- ---------------------------------------------------------------- indexes

create index on public.units (property_id);
create index on public.units (status);
create index on public.leases (unit_id);
create index on public.leases (status);
create index on public.lease_tenants (tenant_id);
create index on public.parking_spaces (lease_id);
create index on public.invoices (lease_id);
create index on public.invoices (period_month);
create index on public.invoices (status);
create index on public.invoice_lines (invoice_id);
create index on public.payments (lease_id);
create index on public.payments (status);
create index on public.payment_allocations (payment_id);
create index on public.payment_allocations (invoice_id);
create index on public.utility_charges (unit_id, period_month);
create index on public.utility_charges (status);
create index on public.work_orders (unit_id);
create index on public.work_orders (status);
create index on public.work_order_notes (work_order_id);
create index on public.work_order_photos (work_order_id);
create index on public.documents (owner_type, owner_id);
create index on public.profiles (tenant_id);

-- ------------------------------------------------------- updated_at wiring

do $$
declare
  t text;
begin
  foreach t in array array[
    'properties','units','tenants','profiles','leases','parking_spaces','lease_tenants',
    'invoices','invoice_lines','payments','payment_allocations','utility_charges',
    'work_orders','work_order_notes','work_order_photos','documents','activity_log','settings'
  ]
  loop
    execute format(
      'create trigger %I before update on public.%I for each row execute function public.set_updated_at()',
      t || '_set_updated_at', t
    );
  end loop;
end;
$$;

-- --------------------------------------------------------- folio sequences

create sequence public.invoice_number_seq start 1;
create sequence public.work_order_folio_seq start 1;

-- Sequential, gap-tolerant folio. Prefix comes from settings.
create or replace function public.next_invoice_number()
returns text
language sql
volatile
security definer
set search_path = public
as $$
  select coalesce((select invoice_prefix from public.settings limit 1), 'REC')
      || '-' || lpad(nextval('public.invoice_number_seq')::text, 5, '0');
$$;

create or replace function public.next_work_order_folio()
returns text
language sql
volatile
security definer
set search_path = public
as $$
  select 'OT-' || lpad(nextval('public.work_order_folio_seq')::text, 5, '0');
$$;

alter table public.work_orders alter column folio set default public.next_work_order_folio();

-- ------------------------------------------------------------------ view

-- Per-lease money position. Cancelled invoices and non-confirmed payments
-- are excluded, which is what every balance card in the app shows.
create view public.lease_balances
with (security_invoker = true)
as
select
  l.id as lease_id,
  coalesce(i.total_invoiced, 0)                            as total_invoiced,
  coalesce(p.total_paid, 0)                                as total_paid,
  coalesce(i.total_invoiced, 0) - coalesce(p.total_paid, 0) as balance,
  i.oldest_overdue_date
from public.leases l
left join lateral (
  select
    sum(inv.total) as total_invoiced,
    min(inv.due_date) filter (
      where inv.due_date < current_date
        and inv.status not in ('pagado', 'cancelado')
    ) as oldest_overdue_date
  from public.invoices inv
  where inv.lease_id = l.id and inv.status <> 'cancelado'
) i on true
left join lateral (
  select sum(pay.amount) as total_paid
  from public.payments pay
  where pay.lease_id = l.id and pay.status = 'confirmado'
) p on true;

-- Money already applied to each invoice. Used to derive pagado / pagado_parcial.
create view public.invoice_balances
with (security_invoker = true)
as
select
  inv.id as invoice_id,
  inv.lease_id,
  inv.total,
  coalesce(a.paid, 0)             as paid,
  inv.total - coalesce(a.paid, 0) as balance
from public.invoices inv
left join lateral (
  select sum(pa.amount) as paid
  from public.payment_allocations pa
  join public.payments pay on pay.id = pa.payment_id
  where pa.invoice_id = inv.id and pay.status = 'confirmado'
) a on true;

insert into public.settings (company_name, invoice_prefix) values ('Rentio', 'REC');


-- ============================================================================
-- 2/13  20260919000200_rls
-- ============================================================================
-- Rentio — row level security. Deny by default, everywhere.
--
-- Storage path convention (enforced by the policies at the bottom):
--   contracts/<lease_id>/<file>
--   tenant-docs/<tenant_id>/<file>
--   payment-receipts/<lease_id>/<file>
--   work-order-photos/<work_order_id>/<file>
--   company/<file>

-- ------------------------------------------------------- helper functions

-- security definer so that reading profiles inside a profiles policy
-- does not recurse through RLS.
create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role in ('admin', 'manager')
  );
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

create or replace function public.my_tenant_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select tenant_id from public.profiles where id = auth.uid();
$$;

create or replace function public.my_lease_ids()
returns setof uuid
language sql
stable
security definer
set search_path = public
as $$
  select lt.lease_id
  from public.lease_tenants lt
  join public.profiles p on p.tenant_id = lt.tenant_id
  where p.id = auth.uid();
$$;

grant execute on function public.is_staff, public.is_admin,
  public.my_tenant_id, public.my_lease_ids to authenticated;

-- ------------------------------------------------------------ enable RLS

do $$
declare
  t text;
begin
  foreach t in array array[
    'properties','units','tenants','profiles','leases','parking_spaces','lease_tenants',
    'invoices','invoice_lines','payments','payment_allocations','utility_charges',
    'work_orders','work_order_notes','work_order_photos','documents','activity_log','settings'
  ]
  loop
    execute format('alter table public.%I enable row level security', t);
  end loop;
end;
$$;

-- ------------------------------------------------- staff-only tables
-- properties, units, utility_charges, settings, activity_log:
-- no tenant access at all.

do $$
declare
  t text;
begin
  foreach t in array array['properties','units','utility_charges','settings','activity_log']
  loop
    execute format('create policy staff_select on public.%I for select to authenticated using (public.is_staff())', t);
    execute format('create policy staff_insert on public.%I for insert to authenticated with check (public.is_staff())', t);
    execute format('create policy staff_update on public.%I for update to authenticated using (public.is_staff()) with check (public.is_staff())', t);
    execute format('create policy admin_delete on public.%I for delete to authenticated using (public.is_admin())', t);
  end loop;
end;
$$;

-- ------------------------------------------------------------- profiles

create policy profiles_select_self on public.profiles
  for select to authenticated using (id = auth.uid() or public.is_staff());
create policy profiles_update_self on public.profiles
  for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
create policy profiles_staff_insert on public.profiles
  for insert to authenticated with check (public.is_staff());
create policy profiles_staff_update on public.profiles
  for update to authenticated using (public.is_staff()) with check (public.is_staff());
create policy profiles_admin_delete on public.profiles
  for delete to authenticated using (public.is_admin());

-- -------------------------------------------------------------- tenants
-- A tenant reads and updates only their own row. Which COLUMNS they may
-- change is enforced by the trigger below — RLS cannot express that.

create policy tenants_staff_all on public.tenants
  for select to authenticated using (public.is_staff() or id = public.my_tenant_id());
create policy tenants_staff_insert on public.tenants
  for insert to authenticated with check (public.is_staff());
create policy tenants_update on public.tenants
  for update to authenticated
  using (public.is_staff() or id = public.my_tenant_id())
  with check (public.is_staff() or id = public.my_tenant_id());
create policy tenants_admin_delete on public.tenants
  for delete to authenticated using (public.is_admin());

create or replace function public.tenants_restrict_self_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if public.is_staff() then
    return new;
  end if;
  -- A tenant editing their own row may only touch contact columns.
  if new.full_name is distinct from old.full_name
     or new.rfc is distinct from old.rfc
     or new.notes is distinct from old.notes then
    raise exception 'Solo puedes actualizar tus datos de contacto';
  end if;
  return new;
end;
$$;

create trigger tenants_restrict_self_update
  before update on public.tenants
  for each row execute function public.tenants_restrict_self_update();

-- --------------------------------------------------------------- leases

create policy leases_select on public.leases
  for select to authenticated
  using (public.is_staff() or id in (select public.my_lease_ids()));
create policy leases_staff_insert on public.leases
  for insert to authenticated with check (public.is_staff());
create policy leases_staff_update on public.leases
  for update to authenticated using (public.is_staff()) with check (public.is_staff());
create policy leases_admin_delete on public.leases
  for delete to authenticated using (public.is_admin());

-- --------------------------------------------------------- lease_tenants

create policy lease_tenants_select on public.lease_tenants
  for select to authenticated
  using (public.is_staff() or lease_id in (select public.my_lease_ids()));
create policy lease_tenants_staff_insert on public.lease_tenants
  for insert to authenticated with check (public.is_staff());
create policy lease_tenants_staff_update on public.lease_tenants
  for update to authenticated using (public.is_staff()) with check (public.is_staff());
create policy lease_tenants_staff_delete on public.lease_tenants
  for delete to authenticated using (public.is_staff());

-- -------------------------------------------------------- parking_spaces

create policy parking_select on public.parking_spaces
  for select to authenticated
  using (public.is_staff() or lease_id in (select public.my_lease_ids()));
create policy parking_staff_insert on public.parking_spaces
  for insert to authenticated with check (public.is_staff());
create policy parking_staff_update on public.parking_spaces
  for update to authenticated using (public.is_staff()) with check (public.is_staff());
create policy parking_admin_delete on public.parking_spaces
  for delete to authenticated using (public.is_admin());

-- ------------------------------------------------------------- invoices

create policy invoices_select on public.invoices
  for select to authenticated
  using (public.is_staff() or lease_id in (select public.my_lease_ids()));
create policy invoices_staff_insert on public.invoices
  for insert to authenticated with check (public.is_staff());
create policy invoices_staff_update on public.invoices
  for update to authenticated using (public.is_staff()) with check (public.is_staff());
create policy invoices_admin_delete on public.invoices
  for delete to authenticated using (public.is_admin());

create policy invoice_lines_select on public.invoice_lines
  for select to authenticated
  using (
    public.is_staff() or exists (
      select 1 from public.invoices i
      where i.id = invoice_id and i.lease_id in (select public.my_lease_ids())
    )
  );
create policy invoice_lines_staff_insert on public.invoice_lines
  for insert to authenticated with check (public.is_staff());
create policy invoice_lines_staff_update on public.invoice_lines
  for update to authenticated using (public.is_staff()) with check (public.is_staff());
create policy invoice_lines_staff_delete on public.invoice_lines
  for delete to authenticated using (public.is_staff());

-- ------------------------------------------------------------- payments
-- Tenants may report a payment, and nothing else. They can never UPDATE.

create policy payments_select on public.payments
  for select to authenticated
  using (public.is_staff() or lease_id in (select public.my_lease_ids()));

create policy payments_tenant_insert on public.payments
  for insert to authenticated
  with check (
    not public.is_staff()
    and lease_id in (select public.my_lease_ids())
    and status = 'pendiente'
    and reported_by_tenant = true
  );

create policy payments_staff_insert on public.payments
  for insert to authenticated with check (public.is_staff());

-- Only an admin may void. Managers can confirm and reject-to-... nothing else.
create policy payments_staff_update on public.payments
  for update to authenticated
  using (public.is_staff())
  with check (public.is_staff() and (status <> 'cancelado' or public.is_admin()));

create policy payments_admin_delete on public.payments
  for delete to authenticated using (public.is_admin());

create policy allocations_select on public.payment_allocations
  for select to authenticated
  using (
    public.is_staff() or exists (
      select 1 from public.payments p
      where p.id = payment_id and p.lease_id in (select public.my_lease_ids())
    )
  );
create policy allocations_staff_insert on public.payment_allocations
  for insert to authenticated with check (public.is_staff());
create policy allocations_staff_update on public.payment_allocations
  for update to authenticated using (public.is_staff()) with check (public.is_staff());
create policy allocations_staff_delete on public.payment_allocations
  for delete to authenticated using (public.is_staff());

-- ---------------------------------------------------------- work_orders

create policy work_orders_select on public.work_orders
  for select to authenticated
  using (public.is_staff() or lease_id in (select public.my_lease_ids()));

create policy work_orders_tenant_insert on public.work_orders
  for insert to authenticated
  with check (
    not public.is_staff()
    and lease_id in (select public.my_lease_ids())
    and source = 'portal'
  );

create policy work_orders_staff_insert on public.work_orders
  for insert to authenticated with check (public.is_staff());
create policy work_orders_staff_update on public.work_orders
  for update to authenticated using (public.is_staff()) with check (public.is_staff());
create policy work_orders_admin_delete on public.work_orders
  for delete to authenticated using (public.is_admin());

-- Internal notes are invisible to tenants. This is the single most
-- important policy in the file — staff write blunt things in them.
create policy wo_notes_select on public.work_order_notes
  for select to authenticated
  using (
    public.is_staff() or (
      is_internal = false and exists (
        select 1 from public.work_orders w
        where w.id = work_order_id and w.lease_id in (select public.my_lease_ids())
      )
    )
  );
create policy wo_notes_staff_insert on public.work_order_notes
  for insert to authenticated with check (public.is_staff());
create policy wo_notes_staff_update on public.work_order_notes
  for update to authenticated using (public.is_staff()) with check (public.is_staff());
create policy wo_notes_staff_delete on public.work_order_notes
  for delete to authenticated using (public.is_staff());

create policy wo_photos_select on public.work_order_photos
  for select to authenticated
  using (
    public.is_staff() or exists (
      select 1 from public.work_orders w
      where w.id = work_order_id and w.lease_id in (select public.my_lease_ids())
    )
  );
create policy wo_photos_insert on public.work_order_photos
  for insert to authenticated
  with check (
    public.is_staff() or exists (
      select 1 from public.work_orders w
      where w.id = work_order_id and w.lease_id in (select public.my_lease_ids())
    )
  );
create policy wo_photos_staff_delete on public.work_order_photos
  for delete to authenticated using (public.is_staff());

-- ------------------------------------------------------------ documents
-- A tenant sees documents attached to their lease or to their own record.

create policy documents_select on public.documents
  for select to authenticated
  using (
    public.is_staff()
    or (owner_type = 'lease'  and owner_id in (select public.my_lease_ids()))
    or (owner_type = 'tenant' and owner_id = public.my_tenant_id())
  );
create policy documents_staff_insert on public.documents
  for insert to authenticated with check (public.is_staff());
create policy documents_staff_update on public.documents
  for update to authenticated using (public.is_staff()) with check (public.is_staff());
create policy documents_staff_delete on public.documents
  for delete to authenticated using (public.is_staff());

-- --------------------------------------------------- tenant-safe settings
-- `settings` itself stays staff-only per spec. The tenant portal needs the
-- bank transfer details, so expose exactly those columns through a
-- security-definer view — nothing else leaks.

create view public.public_settings
with (security_invoker = false)
as
select company_name, logo_url, bank_name, clabe, account_holder, invoice_prefix
from public.settings
limit 1;

grant select on public.public_settings to authenticated;

-- --------------------------------------------------------------- storage

insert into storage.buckets (id, name, public)
values
  ('contracts',         'contracts',         false),
  ('tenant-docs',       'tenant-docs',       false),
  ('payment-receipts',  'payment-receipts',  false),
  ('work-order-photos', 'work-order-photos', false),
  ('company',           'company',           false)
on conflict (id) do nothing;

create policy storage_staff_all on storage.objects
  for all to authenticated
  using (public.is_staff()) with check (public.is_staff());

-- Tenants read only files filed under an id that belongs to them.
create policy storage_tenant_read on storage.objects
  for select to authenticated
  using (
    (bucket_id = 'contracts'
      and ((storage.foldername(name))[1])::uuid in (select public.my_lease_ids()))
    or (bucket_id = 'payment-receipts'
      and ((storage.foldername(name))[1])::uuid in (select public.my_lease_ids()))
    or (bucket_id = 'tenant-docs'
      and ((storage.foldername(name))[1])::uuid = public.my_tenant_id())
    or (bucket_id = 'work-order-photos' and exists (
      select 1 from public.work_orders w
      where w.id = ((storage.foldername(name))[1])::uuid
        and w.lease_id in (select public.my_lease_ids())
    ))
    or bucket_id = 'company'
  );

-- Tenants upload proof of payment and maintenance photos, nothing else.
create policy storage_tenant_write on storage.objects
  for insert to authenticated
  with check (
    (bucket_id = 'payment-receipts'
      and ((storage.foldername(name))[1])::uuid in (select public.my_lease_ids()))
    or (bucket_id = 'work-order-photos' and exists (
      select 1 from public.work_orders w
      where w.id = ((storage.foldername(name))[1])::uuid
        and w.lease_id in (select public.my_lease_ids())
    ))
  );


-- ============================================================================
-- 3/13  20260919000300_portal_views
-- ============================================================================
-- The tenant portal needs the tenant's OWN unit number and building address:
-- it is the payment reference on the Inicio screen and the whole of the
-- Contrato screen. `units` and `properties` stay staff-only per the spec, so
-- this security-definer view exposes exactly those columns, and only for
-- leases the caller is actually on.

create view public.my_lease_details
with (security_invoker = false)
as
select
  l.id            as lease_id,
  u.id            as unit_id,
  u.unit_number,
  u.floor,
  u.bedrooms,
  u.bathrooms,
  u.sqm,
  p.name          as property_name,
  p.street,
  p.colonia,
  p.city,
  p.state,
  p.postal_code
from public.leases l
join public.units u      on u.id = l.unit_id
join public.properties p on p.id = u.property_id
-- Staff read everything; a tenant sees only the leases they are named on.
where public.is_staff() or l.id in (select public.my_lease_ids());

grant select on public.my_lease_details to authenticated;


-- ============================================================================
-- 4/13  20260919000400_public_settings_address
-- ============================================================================
-- The recibo PDF prints the landlord's letterhead — company name, address and
-- bank details — and a tenant must be able to render their own receipt. The
-- address columns were missing from public_settings, so that block came out
-- blank for everyone.
--
-- None of this is sensitive: it is the business address already printed on the
-- receipt the tenant receives. `settings` itself stays staff-only.
--
-- New columns are appended, so `create or replace view` is valid here.

create or replace view public.public_settings
with (security_invoker = false)
as
select
  company_name,
  logo_url,
  bank_name,
  clabe,
  account_holder,
  invoice_prefix,
  street,
  colonia,
  city,
  state,
  postal_code,
  phone,
  email
from public.settings
limit 1;

grant select on public.public_settings to authenticated;


-- ============================================================================
-- 5/13  20260920000500_us_localization
-- ============================================================================
-- Prompt 15 — the properties are in El Paso, Texas, not Mexico.
-- Addresses become US addresses. No business logic changes here.

-- `colonia` has no US equivalent; the field is now a second address line
-- ("Bldg C", "Suite 200").
alter table public.properties rename column colonia to address_line_2;
alter table public.settings   rename column colonia to address_line_2;

-- Existing rows carry Mexican state names. Nothing fits a 2-letter USPS code,
-- so they move to TX; prompt 20 reseeds this data with real El Paso addresses.
update public.properties set state = 'TX' where state is null or state !~ '^[A-Z]{2}$';
update public.settings   set state = 'TX' where state is null or state !~ '^[A-Z]{2}$';

alter table public.properties alter column state set default 'TX';
alter table public.settings   alter column state set default 'TX';

alter table public.properties
  add constraint properties_state_is_usps check (state is null or state ~ '^[A-Z]{2}$'),
  add constraint properties_postal_code_is_zip check (postal_code is null or postal_code ~ '^\d{5}$');

-- `locale` gains a meaning for NULL: "this user has not chosen a language, so
-- use the default for the portal they are in" — English internally, Spanish in
-- the tenant portal. A value set by the user always wins.
alter table public.profiles alter column locale drop not null;
alter table public.profiles alter column locale drop default;
update public.profiles set locale = null;

comment on column public.profiles.locale is
  'User-chosen language. NULL means unset — the portal default applies.';
comment on column public.properties.address_line_2 is
  'Second address line: building, suite, or unit designator.';
comment on column public.units.sqm is
  'Unit area in SQUARE FEET. The column keeps its original name so the '
  'migration does not churn every query; the UI labels it correctly.';

-- A view keeps its own output column names, so both of these still published
-- `colonia` after the rename above.

drop view public.my_lease_details;
create view public.my_lease_details
with (security_invoker = false)
as
select
  l.id            as lease_id,
  u.id            as unit_id,
  u.unit_number,
  u.floor,
  u.bedrooms,
  u.bathrooms,
  u.sqm,
  p.name          as property_name,
  p.street,
  p.address_line_2,
  p.city,
  p.state,
  p.postal_code
from public.leases l
join public.units u      on u.id = l.unit_id
join public.properties p on p.id = u.property_id
where public.is_staff() or l.id in (select public.my_lease_ids());

grant select on public.my_lease_details to authenticated;

drop view public.public_settings;
create view public.public_settings
with (security_invoker = false)
as
select
  company_name,
  logo_url,
  bank_name,
  clabe,
  account_holder,
  invoice_prefix,
  street,
  address_line_2,
  city,
  state,
  postal_code,
  phone,
  email
from public.settings
limit 1;

grant select on public.public_settings to authenticated;


-- ============================================================================
-- 6/13  20260920000501_drop_rfc
-- ============================================================================
-- Prompt 20's cleanup, pulled forward: `rfc` was captured for Mexican tax
-- invoicing (CFDI) that will never happen for a Texas landlord. Removing it
-- here keeps the tenant form and the self-update guard consistent with the
-- rest of the US localization.

alter table public.tenants drop column rfc;

create or replace function public.tenants_restrict_self_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if public.is_staff() then
    return new;
  end if;
  -- A tenant editing their own row may only touch contact columns.
  if new.full_name is distinct from old.full_name
     or new.notes is distinct from old.notes then
    raise exception 'You can only update your own contact details';
  end if;
  return new;
end;
$$;


-- ============================================================================
-- 7/13  20260920000600_us_payment_methods
-- ============================================================================
-- Prompt 16 — US payment rails.
--
-- SPEI, OXXO and CLABE are Mexican. Replace them with what an El Paso
-- landlord actually accepts, and REMOVE the bank fields rather than port
-- them: a full routing + account number published to 120 tenants in the
-- portal is an invitation to unauthorized ACH debits and check fraud. That
-- belongs behind a payment processor in Phase 2, not on a portal page.

-- ----------------------------------------------------------- payment_method

alter type payment_method rename to payment_method_mx;

create type payment_method as enum ('ach', 'zelle', 'check', 'money_order', 'cash', 'card', 'other');

alter table public.payments
  alter column method drop default,
  alter column method type payment_method
    using (case method::text
             when 'spei'     then 'ach'
             when 'efectivo' then 'cash'
             when 'deposito' then 'ach'
             when 'oxxo'     then 'money_order'
             when 'cheque'   then 'check'
             when 'tarjeta'  then 'card'
             else 'other'
           end)::payment_method,
  alter column method set default 'ach';

drop type payment_method_mx;

-- ------------------------------------------------------- payment instructions

-- public_settings still publishes the bank columns, so it has to go first.
drop view public.public_settings;

alter table public.settings
  drop column bank_name,
  drop column clabe,
  drop column account_holder,
  add column zelle_handle         text,
  add column check_payable_to     text,
  add column check_mailing_address text,
  add column dropoff_address      text,
  add column office_hours         text,
  add column payment_notes        text,
  add column nsf_fee              numeric(12,2) not null default 0;

comment on column public.settings.nsf_fee is
  'Returned payment (NSF) fee billed back on a bounced check or failed ACH.';

-- A bounced check has to be billable back to the tenant.
alter type line_category add value if not exists 'nsf_fee';

-- The tenant portal reads its payment instructions from here. Everything in
-- this view is information the landlord is deliberately handing to tenants;
-- `settings` itself stays staff-only.
create view public.public_settings
with (security_invoker = false)
as
select
  company_name,
  logo_url,
  invoice_prefix,
  street,
  address_line_2,
  city,
  state,
  postal_code,
  phone,
  email,
  zelle_handle,
  check_payable_to,
  check_mailing_address,
  dropoff_address,
  office_hours,
  payment_notes
from public.settings
limit 1;

grant select on public.public_settings to authenticated;


-- ============================================================================
-- 8/13  20260920000700_texas_late_fees
-- ============================================================================
-- Prompt 17 — Texas Property Code §92.019 constrains residential late fees.
--
-- Two rules the schema has to make it hard to break:
--   1. No late fee may be charged unless the rent is still unpaid at the END
--      OF THE SECOND FULL DAY after it was due. The minimum enforceable grace
--      period is therefore 2 days — never 0 and never 1.
--   2. A fee is PRESUMED reasonable at up to a percentage of one month's
--      rent: 12% for a dwelling in a structure of 4 or fewer units, 10% for a
--      structure with more than 4. A presumption is not an absolute ceiling,
--      so the app warns rather than blocks above it.

create type late_fee_type as enum ('fixed', 'percent');

-- ------------------------------------------------------------- properties

-- Nullable on purpose: when it is null the app derives the count from the
-- units on the property. A "property" in this app may be several separate
-- buildings, in which case the derivation is wrong and this is set by hand.
alter table public.properties
  add column units_in_structure int
    check (units_in_structure is null or units_in_structure > 0);

comment on column public.properties.units_in_structure is
  'Dwelling units in this physical structure. Sets the §92.019 late fee cap: '
  '12% at 4 or fewer, 10% above. NULL derives it from the unit count.';

-- ----------------------------------------------------------------- leases

alter table public.leases
  add column late_fee_type    late_fee_type not null default 'percent',
  add column late_fee_percent numeric(5,2) not null default 0
    check (late_fee_percent >= 0 and late_fee_percent <= 100),
  -- Set when a manager knowingly saves a fee above the presumed-reasonable
  -- cap. Without this the lease form refuses to save one.
  add column late_fee_over_cap_ack boolean not null default false;

-- Existing leases carry a flat fee and whatever grace period was typed in.
-- Convert them to a percentage of rent, clamped to the statutory presumption,
-- and lift every grace period to the legal minimum.
update public.leases
set late_fee_type = 'percent',
    late_fee_percent = least(
      round(case when rent_amount > 0
                 then (late_fee_amount / rent_amount) * 100
                 else 0 end, 2),
      10
    );

update public.leases set grace_days = 2 where grace_days < 2;

-- The backstop. A UI check alone is not enough for a legal constraint.
alter table public.leases
  add constraint leases_grace_days_texas_minimum check (grace_days >= 2);

comment on constraint leases_grace_days_texas_minimum on public.leases is
  'Texas Property Code §92.019: rent must be unpaid at the end of the second '
  'full day after the due date before a late fee may be charged.';

-- --------------------------------------------------------------- settings

alter table public.settings
  add column default_late_fee_percent numeric(5,2) not null default 10
    check (default_late_fee_percent >= 0 and default_late_fee_percent <= 100);

alter table public.settings drop column default_late_fee;

update public.settings set default_grace_days = greatest(default_grace_days, 2);

alter table public.settings
  add constraint settings_grace_days_texas_minimum check (default_grace_days >= 2);


-- ============================================================================
-- 9/13  20260920000800_deposit_clock
-- ============================================================================
-- Prompt 18 — Texas Property Code §92.103–92.109, security deposit returns.
--
-- The landlord must refund the deposit within 30 days after the tenant
-- surrenders the premises AND provides a forwarding address, and must deliver
-- an itemized list of any deductions. Retaining a deposit in bad faith
-- exposes the landlord to statutory penalties plus attorney's fees.
--
-- The two events are separate, and only the second starts the clock. Modelled
-- as a tracked obligation with a computed deadline, not a notes field.

alter table public.leases
  add column surrender_date                 date,
  add column forwarding_address             text,
  add column forwarding_address_received_at date,
  -- Generated, so the deadline cannot drift from the date that set it.
  add column deposit_due_date date
    generated always as (forwarding_address_received_at + 30) stored,
  add column deposit_settled_at date,
  add column deposit_itemization jsonb not null default '[]'::jsonb,
  add column move_out_notes text,
  -- The clock cannot start before the tenant has actually moved out.
  add constraint leases_forwarding_after_surrender check (
    forwarding_address_received_at is null
    or surrender_date is null
    or forwarding_address_received_at >= surrender_date
  );

comment on column public.leases.deposit_due_date is
  'Texas Property Code §92.103: 30 days after the forwarding address is '
  'received. Generated — never set this by hand.';
comment on column public.leases.deposit_itemization is
  'Array of {description, amount}. §92.104(c) requires an itemized list '
  'whenever any part of the deposit is withheld.';

create index on public.leases (deposit_due_date)
  where deposit_settled_at is null;

-- Deposits still owed, with the clock's current state. One place, so the
-- dashboard card and the compliance report cannot disagree.
create view public.deposit_obligations
with (security_invoker = true)
as
select
  l.id                as lease_id,
  l.unit_id,
  l.deposit_amount,
  l.surrender_date,
  l.forwarding_address,
  l.forwarding_address_received_at,
  l.deposit_due_date,
  l.deposit_settled_at,
  l.deposit_itemization,
  (l.deposit_due_date - current_date)                as days_remaining,
  (l.deposit_settled_at - l.forwarding_address_received_at) as days_taken,
  case
    when l.deposit_settled_at is not null
      then l.deposit_settled_at <= l.deposit_due_date
    else null
  end                                                as settled_on_time
from public.leases l
where l.surrender_date is not null;

grant select on public.deposit_obligations to authenticated;


-- ============================================================================
-- 10/13  20260920000900_texas_repairs_notices_turnover
-- ============================================================================
-- Prompt 19 — three smaller Texas Property Code obligations.

-- ---------------------------------------- 1. repair notice (§92.052, §92.056)
--
-- The duty to repair a condition materially affecting health or safety is
-- triggered by the tenant's WRITTEN notice, and 7 days is presumed a
-- reasonable time to repair. A portal-submitted work order IS written notice,
-- which is an advantage for the client, so it is recorded as one.

alter table public.work_orders
  add column affects_health_safety boolean not null default false,
  add column written_notice_at timestamptz;

comment on column public.work_orders.written_notice_at is
  'When the tenant gave written notice. §92.056 presumes 7 days a reasonable '
  'time to repair from this moment. Set automatically for portal orders.';

-- Backfill: every existing portal order already was written notice.
update public.work_orders set written_notice_at = created_at where source = 'portal';

create or replace function public.work_orders_set_written_notice()
returns trigger
language plpgsql
as $$
begin
  -- A portal submission is the tenant's own written notice, so it dates from
  -- when they sent it, not from when a manager happened to flag it.
  if new.source = 'portal' and new.written_notice_at is null then
    new.written_notice_at := coalesce(new.created_at, now());
  end if;
  return new;
end;
$$;

create trigger work_orders_set_written_notice
  before insert or update on public.work_orders
  for each row execute function public.work_orders_set_written_notice();

create index on public.work_orders (written_notice_at)
  where affects_health_safety and resolved_at is null;

-- ------------------------------------------ 2. notice to vacate (§24.005)

create type notice_type as enum ('non_payment', 'lease_violation', 'end_of_term');
create type notice_delivery as enum ('in_person', 'mail', 'affixed_to_door');

create table public.lease_notices (
  id             uuid primary key default gen_random_uuid(),
  lease_id       uuid not null references public.leases (id) on delete cascade,
  type           notice_type not null,
  reason         text,
  vacate_date    date not null,
  delivery       notice_delivery not null,
  delivered_at   date not null default current_date,
  document_url   text,
  created_by     uuid references public.profiles (id) on delete set null,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz
);

comment on table public.lease_notices is
  'A record that a notice to vacate was generated and delivered. §24.005 '
  'governs the notice itself. This files NOTHING with a court.';

create index on public.lease_notices (lease_id);

-- ------------------- 3. move-in / turnover checklist (§92.156, §92.251–92.261)
--
-- Security devices must be rekeyed no later than the 7th day after a new
-- tenant takes possession, and smoke alarms maintained.

create table public.unit_turnover_checklist (
  id           uuid primary key default gen_random_uuid(),
  unit_id      uuid not null references public.units (id) on delete cascade,
  lease_id     uuid not null references public.leases (id) on delete cascade,
  item         text not null,
  -- Ordering key, and what the rekey countdown keys off.
  item_key     text not null,
  position     int not null default 0,
  completed    boolean not null default false,
  completed_at timestamptz,
  completed_by uuid references public.profiles (id) on delete set null,
  notes        text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz,
  unique (lease_id, item_key)
);

create index on public.unit_turnover_checklist (unit_id);
create index on public.unit_turnover_checklist (lease_id);

-- Keep completed_at honest without making every caller remember to set it.
create or replace function public.turnover_set_completed_at()
returns trigger
language plpgsql
as $$
begin
  if new.completed and not coalesce(old.completed, false) then
    new.completed_at := coalesce(new.completed_at, now());
  elsif not new.completed then
    new.completed_at := null;
    new.completed_by := null;
  end if;
  return new;
end;
$$;

create trigger turnover_set_completed_at
  before update on public.unit_turnover_checklist
  for each row execute function public.turnover_set_completed_at();

-- updated_at, same as every other table.
create trigger lease_notices_set_updated_at
  before update on public.lease_notices
  for each row execute function public.set_updated_at();
create trigger unit_turnover_checklist_set_updated_at
  before update on public.unit_turnover_checklist
  for each row execute function public.set_updated_at();

-- ------------------------------------------------------------------- RLS
--
-- Deny by default, like every other table. Both of these are internal
-- records: a tenant has no business reading the turnover checklist, and a
-- notice reaches them as a delivered document, not as a row they can poll.

alter table public.lease_notices enable row level security;
alter table public.unit_turnover_checklist enable row level security;

create policy lease_notices_staff_select on public.lease_notices
  for select to authenticated using (public.is_staff());
create policy lease_notices_staff_insert on public.lease_notices
  for insert to authenticated with check (public.is_staff());
create policy lease_notices_staff_update on public.lease_notices
  for update to authenticated using (public.is_staff()) with check (public.is_staff());
create policy lease_notices_admin_delete on public.lease_notices
  for delete to authenticated using (public.is_admin());

create policy turnover_staff_select on public.unit_turnover_checklist
  for select to authenticated using (public.is_staff());
create policy turnover_staff_insert on public.unit_turnover_checklist
  for insert to authenticated with check (public.is_staff());
create policy turnover_staff_update on public.unit_turnover_checklist
  for update to authenticated using (public.is_staff()) with check (public.is_staff());
create policy turnover_admin_delete on public.unit_turnover_checklist
  for delete to authenticated using (public.is_admin());


-- ============================================================================
-- 11/13  20260920001000_late_fee_guard
-- ============================================================================
-- Prompt 17 said "do not let a manager bypass the 2-day rule anywhere in the
-- UI". The gated "Apply late fee" button honoured it; "Add line" did not.
-- A manager could pick the "Late fee" category by hand and write a fee of any
-- size to an invoice due today. Verified against the live database before
-- this migration: a $999 late fee inserted with no check at all.
--
-- The button is not the guard. This is.

create or replace function public.enforce_late_fee_rules()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  inv        record;
  grace      int;
  eligible   date;
  existing   int;
begin
  if new.category <> 'recargo' then
    return new;
  end if;

  select i.due_date, i.lease_id into inv
  from public.invoices i where i.id = new.invoice_id;

  if not found then
    return new;
  end if;

  select greatest(l.grace_days, 2) into grace
  from public.leases l where l.id = inv.lease_id;

  -- §92.019(a): the rent must still be unpaid at the END of the second full
  -- day after it was due, so the fee is chargeable from the day after that.
  -- A longer grace period in the lease wins.
  eligible := inv.due_date + coalesce(grace, 2) + 1;

  if current_date < eligible then
    raise exception using
      errcode = 'check_violation',
      message = format(
        'Texas Property Code 92.019: a late fee on this invoice cannot be charged before %s.',
        to_char(eligible, 'MM/DD/YYYY')
      );
  end if;

  -- One late fee per invoice, whichever path wrote it.
  select count(*) into existing
  from public.invoice_lines il
  where il.invoice_id = new.invoice_id
    and il.category = 'recargo'
    and il.id <> coalesce(new.id, '00000000-0000-0000-0000-000000000000'::uuid);

  if existing > 0 then
    raise exception using
      errcode = 'check_violation',
      message = 'This invoice already has a late fee.';
  end if;

  return new;
end;
$$;

create trigger invoice_lines_enforce_late_fee_rules
  before insert or update on public.invoice_lines
  for each row execute function public.enforce_late_fee_rules();


-- ============================================================================
-- 12/13  20260922001100_access_requests
-- ============================================================================
-- A tenant with no invite needs somewhere to go.
--
-- The old "Set up portal access" screen asked for the email address the
-- office had on file, which a tenant usually does not know, and when there
-- was no match it said nothing and did nothing. This is the queue that turns
-- that dead end into a request a human can act on.

create type access_request_status as enum ('pending', 'approved', 'declined');

create table public.access_requests (
  id                uuid primary key default gen_random_uuid(),
  full_name         text not null,
  email             text not null,
  phone             text,
  -- What the person typed, not a foreign key: they are describing where they
  -- live in their own words, which is the whole point of the form.
  property_hint     text,
  unit_hint         text,
  status            access_request_status not null default 'pending',
  -- Best-effort match found at submission time, for staff to confirm or
  -- override. Never shown to the requester.
  matched_tenant_id uuid references public.tenants (id) on delete set null,
  note              text,
  reviewed_by       uuid references public.profiles (id) on delete set null,
  reviewed_at       timestamptz,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz
);

comment on table public.access_requests is
  'Portal access requests from people with no invite. Written only by the '
  'submit-access-request edge function under the service role; the table '
  'itself is staff-only.';

create index on public.access_requests (status, created_at desc);

create trigger access_requests_set_updated_at
  before update on public.access_requests
  for each row execute function public.set_updated_at();

-- ------------------------------------------------------------------- RLS
--
-- Staff-only, exactly like lease_notices. The public form does NOT insert
-- here directly: there is not one `to anon` policy anywhere in this schema,
-- and the only other anonymous endpoint (tenant-self-enroll) goes through an
-- edge function with the service role for the same reason. An anon-writable
-- table is an unauthenticated write sink with no place to validate or rate
-- limit.

alter table public.access_requests enable row level security;

create policy access_requests_staff_select on public.access_requests
  for select to authenticated using (public.is_staff());
create policy access_requests_staff_insert on public.access_requests
  for insert to authenticated with check (public.is_staff());
create policy access_requests_staff_update on public.access_requests
  for update to authenticated using (public.is_staff()) with check (public.is_staff());
create policy access_requests_admin_delete on public.access_requests
  for delete to authenticated using (public.is_admin());


-- ============================================================================
-- 13/13  DEMO DATA
-- ============================================================================
-- Rentio — demo data (El Paso, Texas).
-- Safe to re-run: it clears the demo tables first.
--
-- Deliberately leaves 4 active leases WITHOUT an invoice for the current
-- month, and their utility charges `pendiente`, so "Generate this month's
-- receipts" has real work to do on a fresh demo. It also leaves one health
-- and safety work order past its 7-day statutory window and one terminated
-- lease with the deposit clock running, so both compliance warnings are
-- visible without anyone having to set them up.

begin;

-- DELETE, not TRUNCATE ... CASCADE, and the difference matters.
--
-- `profiles.tenant_id` is declared `on delete set null`. DELETE honours that:
-- the profile row survives with its tenant link cleared. TRUNCATE CASCADE
-- ignores it and truncates every referencing table wholesale, which took out
-- `profiles` — including the admin and manager accounts, which have nothing
-- to do with the demo data. Every reseed silently destroyed every login until
-- db:demo-logins was run again, and if it was not, the next person to sign in
-- authenticated fine and landed with no role at all.
--
-- These are listed children-first so the foreign keys are satisfied.
delete from public.activity_log;
delete from public.documents;
delete from public.work_order_photos;
delete from public.work_order_notes;
delete from public.work_orders;
delete from public.utility_charges;
delete from public.payment_allocations;
delete from public.payments;
delete from public.invoice_lines;
delete from public.invoices;
delete from public.lease_notices;
delete from public.unit_turnover_checklist;
delete from public.lease_tenants;
delete from public.parking_spaces;
delete from public.leases;
delete from public.units;
delete from public.tenants;
delete from public.properties;

alter sequence public.invoice_number_seq restart with 1;
alter sequence public.work_order_folio_seq restart with 1;

update public.settings set
  company_name   = 'Sun City Property Management',
  invoice_prefix = 'REC',
  default_late_fee_percent = 10.00,
  default_grace_days = 2,
  nsf_fee = 35.00,
  street = '4141 Pinnacle St',
  address_line_2 = 'Suite 210',
  city = 'El Paso',
  state = 'TX',
  postal_code = '79902',
  phone = '(915) 555-1200',
  email = 'office@suncitypm.com',
  -- Only the methods this landlord actually accepts. The portal renders
  -- exactly these rows and no empty ones.
  zelle_handle = 'payments@suncitypm.com',
  check_payable_to = 'Sun City Property Management LLC',
  check_mailing_address = E'Sun City Property Management LLC\n4141 Pinnacle St, Suite 210\nEl Paso, TX 79902',
  dropoff_address = E'4141 Pinnacle St, Suite 210\nEl Paso, TX 79902',
  office_hours = 'Mon–Fri 9:00 AM – 5:00 PM',
  payment_notes = 'Include your unit number on the memo line so we can match your payment.';

-- ------------------------------------------------------------ properties
-- Westside, Northeast and the Lower Valley. `units_in_structure` is set by
-- hand because it drives the §92.019 late fee cap: the fourplex takes the
-- 12% presumption, the two apartment buildings 10%.

insert into public.properties (name, street, address_line_2, city, state, postal_code, units_in_structure, notes) values
  ('Mesa Hills Apartments',  '5820 Mesa Hills Dr', 'Bldg A', 'El Paso', 'TX', '79912', 14, 'Westside. Renovated 2021. Gated parking, laundry on site.'),
  ('Dyer Street Commons',    '9315 Dyer St',       NULL,     'El Paso', 'TX', '79924', 14, 'Northeast, near Fort Bliss. Covered parking, on-site manager Mon–Fri.'),
  ('Ysleta Court',           '8402 Alameda Ave',   'Bldg C', 'El Paso', 'TX', '79907',  4, 'Lower Valley. Single fourplex — takes the 12% late fee cap.');

-- ----------------------------------------------------------------- units
-- 40 units: 14 / 14 / 12. Rent lands between $650 and $1,600, which is
-- where El Paso actually is. Demo numbers that look wrong undermine a demo.

insert into public.units (property_id, unit_number, floor, bedrooms, bathrooms, sqm, base_rent, status)
select
  p.id,
  (((i - 1) / 4 + 1) * 100 + ((i - 1) % 4 + 1))::text,
  (i - 1) / 4 + 1,
  b.bedrooms,
  case when b.bedrooms = 1 then 1.0 when b.bedrooms = 2 then 1.5 else 2.0 end,
  round((520 + b.bedrooms * 240 + (i % 4) * 35)::numeric, 2),
  round((650 + (b.bedrooms - 1) * 300 + cfg.premium + (i % 5) * 40)::numeric, 2),
  'vacante'
from (values
  ('Mesa Hills Apartments', 14, 180),
  ('Dyer Street Commons',   14,  60),
  ('Ysleta Court',          12,   0)
) as cfg(pname, n, premium)
join public.properties p on p.name = cfg.pname
cross join lateral generate_series(1, cfg.n) as i
cross join lateral (select (i % 3) + 1 as bedrooms) b;

-- -------------------------------------------------------- parking spaces
-- 25 spaces: 10 / 9 / 6.

insert into public.parking_spaces (property_id, label, type, monthly_fee, status)
select
  p.id,
  'P-' || lpad(i::text, 2, '0'),
  case when i % 3 = 0 then 'descubierto' else 'techado' end,
  case when i % 3 = 0 then 25.00 else 45.00 end,
  'disponible'
from (values ('Mesa Hills Apartments', 10), ('Dyer Street Commons', 9), ('Ysleta Court', 6)) as cfg(pname, n)
join public.properties p on p.name = cfg.pname
cross join lateral generate_series(1, cfg.n) as i;

-- --------------------------------------------------------------- tenants
-- A realistic El Paso mix: roughly four in five Hispanic surnames, the rest
-- not, with (915) numbers throughout.
--
-- The first three carry FIXED ids. Everything in this file is dropped and
-- recreated on every reseed, so tenants used to come back with new uuids and,
-- because db:demo-logins picked "the first three primary tenants", a
-- different three people got portal logins each time. The demo tenant
-- credentials changed underneath whoever was about to demo. Pinning these
-- three ids makes the demo logins stable for good; the other 27 are ordinary
-- rows and may churn freely.

insert into public.tenants (id, full_name, email, phone, emergency_contact_name, emergency_contact_phone)
select
  case n.i
    when 1 then '00000000-0000-4000-8000-00000000d001'::uuid
    when 2 then '00000000-0000-4000-8000-00000000d002'::uuid
    when 3 then '00000000-0000-4000-8000-00000000d003'::uuid
    else gen_random_uuid()
  end,
  n.full_name,
  lower(
    translate(split_part(n.full_name, ' ', 1), 'áéíóúÁÉÍÓÚñÑ', 'aeiouAEIOUnN') || '.' ||
    translate(split_part(n.full_name, ' ', 2), 'áéíóúÁÉÍÓÚñÑ', 'aeiouAEIOUnN')
  ) || '@example.com',
  '(915) ' || lpad((200 + n.i * 7)::text, 3, '0') || '-' || lpad((1000 + n.i * 53)::text, 4, '0'),
  n.emergency,
  '(915) ' || lpad((300 + n.i * 11)::text, 3, '0') || '-' || lpad((2000 + n.i * 61)::text, 4, '0')
from (
  select row_number() over () as i, full_name, emergency from (values
    ('María Fernanda Ríos',      'Jorge Ríos Medina'),
    ('Daniel Whitaker',          'Susan Whitaker'),
    ('Ana Sofía Hernández',      'Miguel Hernández Cruz'),
    ('Luis Enrique Ramírez',     'Patricia Ramírez Ortiz'),
    ('Gabriela Mendoza',         'Raúl Mendoza Lara'),
    ('Ricardo Alonso Vargas',    'Claudia Vargas Nieto'),
    ('Alejandra Castillo',       'Héctor Castillo Ruiz'),
    ('Marcus Thompson',          'Denise Thompson'),
    ('Paola Jiménez Soto',       'Andrés Jiménez Rocha'),
    ('Roberto Núñez Salas',      'Elena Núñez Vega'),
    ('Diana Laura Ortega',       'Sergio Ortega Campos'),
    ('Miguel Ángel Domínguez',   'Rosa Domínguez Islas'),
    ('Katherine O''Brien',       'Patrick O''Brien'),
    ('José Antonio Reyes',       'Silvia Reyes Cabrera'),
    ('Verónica Salazar',         'Arturo Salazar Peña'),
    ('Héctor Iván Morales',      'Beatriz Morales Luna'),
    ('Claudia Patricia Cruz',    'Ramón Cruz Estrada'),
    ('Eduardo Barrera Lima',     'Mónica Barrera Téllez'),
    ('Brandon Nguyen',           'Linda Nguyen'),
    ('Sergio Alberto Navarro',   'Adriana Navarro Fuentes'),
    ('Lucía Beltrán Arriaga',    'Emilio Beltrán Cano'),
    ('Óscar Daniel Cervantes',   'Teresa Cervantes Lozano'),
    ('Rocío Guadalupe Andrade',  'Javier Andrade Pineda'),
    ('Armando Téllez Rosas',     'Guadalupe Téllez Mora'),
    ('Rachel Goldstein',         'David Goldstein'),
    ('Pablo Emilio Zamora',      'Cecilia Zamora Rangel'),
    ('Nadia Escobar Ponce',      'Ignacio Escobar Ávila'),
    ('Rubén Darío Maldonado',    'Alicia Maldonado Bravo'),
    ('Tyler Brooks',             'Megan Brooks'),
    ('Emiliano Rivas Cuéllar',   'Daniela Rivas Montes')
  ) as t(full_name, emergency)
) n;

-- ---------------------------------------------------------------- leases
-- 30 active leases on the first 30 units, plus one terminated lease whose
-- deposit clock is running. Four end within 60 days so the "Por vencer"
-- badge has something to show.
--
-- Every lease is on the Texas default: a percentage late fee at 10% and the
-- statutory minimum 2-day grace period. Deposits are one month's rent.

with ordered_units as (
  select u.id, u.base_rent, row_number() over (order by p.name, u.unit_number) as rn
  from public.units u join public.properties p on p.id = u.property_id
)
insert into public.leases (
  unit_id, start_date, end_date, rent_amount, rent_due_day, grace_days,
  late_fee_type, late_fee_percent, late_fee_amount, deposit_amount, status
)
select
  ou.id,
  d.start_date,
  (d.start_date + interval '12 months' - interval '1 day')::date,
  ou.base_rent,
  case when ou.rn % 4 = 0 then 5 else 1 end,
  2,
  'percent',
  10.00,
  0,
  ou.base_rent,
  'activo'
from ordered_units ou
cross join lateral (
  select case
    when ou.rn <= 4 then (date_trunc('month', current_date) - interval '11 months' + interval '10 days')::date
    else (date_trunc('month', current_date) - ((ou.rn % 9) + 2) * interval '1 month')::date
  end as start_date
) d
where ou.rn <= 30;

update public.units u set status = 'ocupada'
where exists (select 1 from public.leases l where l.unit_id = u.id and l.status = 'activo');

-- A little texture in the remaining 10 vacant units.
with spare as (
  select u.id, row_number() over (order by u.created_at, u.unit_number) as rn
  from public.units u where u.status = 'vacante'
)
update public.units u set status = case when s.rn <= 2 then 'mantenimiento'::unit_status else 'reservada'::unit_status end
from spare s where u.id = s.id and s.rn <= 4;

-- ---------------------------------------------------------- lease tenants

with l as (
  select id, row_number() over (order by created_at, id) as rn from public.leases
), t as (
  select id, row_number() over (order by created_at, id) as rn from public.tenants
)
insert into public.lease_tenants (lease_id, tenant_id, role)
select l.id, t.id, 'primary' from l join t on t.rn = l.rn;

-- Every fifth lease gets a co-tenant, every seventh a guarantor.
with l as (
  select id, row_number() over (order by created_at, id) as rn from public.leases
), t as (
  select id, row_number() over (order by created_at, id) as rn from public.tenants
)
insert into public.lease_tenants (lease_id, tenant_id, role)
select l.id, t.id, r.role
from l
join lateral (values ('co_tenant'::lease_tenant_role, 5, 1), ('guarantor'::lease_tenant_role, 7, 2)) as r(role, modulo, offs) on l.rn % r.modulo = 0
join t on t.rn = ((l.rn + r.offs - 1) % 30) + 1
on conflict (lease_id, tenant_id) do nothing;

-- ---------------------------------------------- move-in / turnover lists
-- §92.156 — rekey within 7 days of possession. Every lease that has been
-- running for months is fully turned over; the two brand-new move-ins added
-- at the bottom of this file are the ones still in progress.

insert into public.unit_turnover_checklist (unit_id, lease_id, item, item_key, position, completed, completed_at)
select
  l.unit_id, l.id, c.item, c.item_key, c.position,
  true,
  l.start_date + interval '2 days'
from public.leases l
cross join (values
  ('Rekey locks (required within 7 days)',          'rekey_locks',               0),
  ('Test smoke alarms',                             'test_smoke_alarms',         1),
  ('Verify deadbolt and keyless bolting device',    'verify_deadbolt_keyless',   2),
  ('Verify window latches',                         'verify_window_latches',     3),
  ('Document unit condition with photos',           'document_condition_photos', 4),
  ('Collect renters insurance certificate',         'collect_renters_insurance', 5)
) as c(item, item_key, position)
on conflict (lease_id, item_key) do nothing;

-- ------------------------------------------------------ parking assignment
-- 15 of 25 spaces assigned, always to a lease in the same property.

with ranked_spaces as (
  select ps.id, ps.property_id, row_number() over (partition by ps.property_id order by ps.label) as rn
  from public.parking_spaces ps
), ranked_leases as (
  select l.id as lease_id, u.property_id, row_number() over (partition by u.property_id order by u.unit_number) as rn
  from public.leases l join public.units u on u.id = l.unit_id where l.status = 'activo'
)
update public.parking_spaces ps
set lease_id = rl.lease_id, status = 'asignado'
from ranked_spaces rs
join ranked_leases rl on rl.property_id = rs.property_id and rl.rn = rs.rn
where ps.id = rs.id and rs.rn <= 5;

update public.parking_spaces set status = 'fuera_de_servicio'
where lease_id is null and label in ('P-09', 'P-10');

-- ------------------------------------------------------- utility charges
-- Two billed months behind us, the current month still pendiente.

insert into public.utility_charges (unit_id, lease_id, type, period_month, amount, status, notes)
select
  l.unit_id,
  l.id,
  ut.type,
  (date_trunc('month', current_date) - m.offset_months * interval '1 month')::date,
  ut.amount,
  case when m.offset_months = 0 then 'pendiente'::utility_status else 'facturado'::utility_status end,
  null
from public.leases l
join lateral (
  select row_number() over (order by l2.created_at, l2.id) as rn from public.leases l2 where l2.id = l.id
) r on true
cross join lateral (values (0), (1), (2)) as m(offset_months)
cross join lateral (values
  ('agua'::utility_type, round((28 + (r.rn % 7) * 4)::numeric, 2)),
  ('cuota_mantenimiento'::utility_type, 35.00)
) as ut(type, amount)
where l.status = 'activo'
on conflict (unit_id, type, period_month) do nothing;

-- --------------------------------------------------------------- invoices
-- Months M-2 and M-1 for all 30 leases; month M for 26 of them.

with l as (
  select l.*, row_number() over (order by l.created_at, l.id) as rn from public.leases l where l.status = 'activo'
),
periods as (select * from (values (2), (1), (0)) as p(offset_months)),
target as (
  select l.*, p.offset_months,
         (date_trunc('month', current_date) - p.offset_months * interval '1 month')::date as period_month
  from l cross join periods p
  where not (p.offset_months = 0 and l.rn > 26)   -- 4 leases left for the generator to pick up
),
ins as (
  insert into public.invoices (lease_id, period_month, invoice_number, issue_date, due_date, status, total)
  select
    t.id,
    t.period_month,
    public.next_invoice_number(),
    t.period_month,
    (t.period_month + (least(t.rent_due_day, 28) - 1) * interval '1 day')::date,
    case when t.offset_months = 0 then 'enviado'::invoice_status else 'pagado'::invoice_status end,
    0
  from target t
  order by t.period_month, t.rn
  returning id, lease_id, period_month
)
insert into public.invoice_lines (invoice_id, description, category, quantity, amount)
-- rent
select i.id, 'Monthly rent', 'renta'::line_category, 1::numeric, l.rent_amount
from ins i join public.leases l on l.id = i.lease_id
union all
-- parking
select i.id, 'Parking ' || ps.label, 'estacionamiento'::line_category, 1::numeric, ps.monthly_fee
from ins i join public.parking_spaces ps on ps.lease_id = i.lease_id
union all
-- utilities already billed
select i.id,
       case uc.type when 'agua' then 'Water' when 'cuota_mantenimiento' then 'Common area fee' else 'Utility' end,
       case uc.type when 'cuota_mantenimiento' then 'cuota_mantenimiento'::line_category else 'servicios'::line_category end,
       1::numeric, uc.amount
from ins i
join public.utility_charges uc on uc.lease_id = i.lease_id and uc.period_month = i.period_month and uc.status = 'facturado';

-- Point the consumed charges at the invoice that ate them.
update public.utility_charges uc
set invoice_id = i.id
from public.invoices i
where uc.lease_id = i.lease_id and uc.period_month = i.period_month and uc.status = 'facturado';

-- Totals always come from the lines.
update public.invoices i
set total = coalesce((select sum(il.amount * il.quantity) from public.invoice_lines il where il.invoice_id = i.id), 0);

-- --------------------------------------------------------------- payments
-- M-2: everyone paid. M-1: most paid, a few short. M: about half paid.
-- Spread across ACH, Zelle, check and money order, with a reference that
-- reads the way that method's reference actually reads.

with inv as (
  select i.*, row_number() over (order by i.period_month, i.invoice_number) as rn,
         (date_part('month', age(date_trunc('month', current_date), i.period_month)))::int
         + (date_part('year', age(date_trunc('month', current_date), i.period_month)))::int * 12 as months_ago
  from public.invoices i
),
payable as (
  select inv.*,
    case
      when months_ago = 2 then inv.total                                   -- fully paid
      when months_ago = 1 and inv.rn % 10 = 0 then round(inv.total * 0.5, 2)  -- partial
      when months_ago = 1 and inv.rn % 10 = 3 then 0                       -- never paid -> vencido
      when months_ago = 1 then inv.total
      when months_ago = 0 and inv.rn % 2 = 0 then inv.total                -- current month, half paid
      else 0
    end as pay_amount,
    (array['ach','ach','zelle','check','money_order'])[(inv.rn % 5) + 1]::payment_method as pay_method,
    -- Derived from the invoice's row number, so it stays the key that ties
    -- each payment back to exactly one invoice.
    case (inv.rn % 5) + 1
      when 1 then 'ACH-' || lpad((7000000 + inv.rn * 137)::text, 9, '0')
      when 2 then 'ACH-' || lpad((7000000 + inv.rn * 137)::text, 9, '0')
      when 3 then 'Zelle ' || lpad((7000000 + inv.rn * 137)::text, 9, '0')
      when 4 then 'Check #' || lpad((7000000 + inv.rn * 137)::text, 9, '0')
      else 'MO ' || lpad((7000000 + inv.rn * 137)::text, 9, '0')
    end as pay_reference
  from inv
),
pay as (
  insert into public.payments (lease_id, amount, paid_at, method, reference, status, reported_by_tenant, confirmed_at)
  select
    p.lease_id,
    p.pay_amount,
    least(p.due_date + ((p.rn % 4))::int, current_date),
    p.pay_method,
    p.pay_reference,
    'confirmado',
    false,
    now()
  from payable p
  where p.pay_amount > 0
  returning id, amount, reference
)
insert into public.payment_allocations (payment_id, invoice_id, amount)
select pay.id, payable.id, pay.amount
from pay
join payable on payable.pay_reference = pay.reference;

-- Three self-reported payments waiting in the confirmation queue.
insert into public.payments (lease_id, amount, paid_at, method, reference, status, reported_by_tenant, notes)
select l.id, l.rent_amount, current_date - 1, 'zelle',
       'Zelle ' || lpad((9100000 + row_number() over ())::text, 9, '0'),
       'pendiente', true, 'Sent from my Chase account this morning.'
from public.leases l
where l.status = 'activo'
order by l.created_at
limit 3;

-- Derive invoice status from what was actually allocated.
update public.invoices i
set status = case
  when i.status = 'cancelado' then i.status
  when b.paid >= i.total then 'pagado'
  when b.paid > 0 then 'pagado_parcial'
  when i.due_date < current_date then 'vencido'
  else 'enviado'
end
from public.invoice_balances b
where b.invoice_id = i.id;

-- ------------------------------------------------------------ work orders
-- 15 orders across every status, category and source. Three are flagged as
-- health and safety; the first of those is deliberately past its 7-day
-- statutory window so the dashboard warning is visible in the demo.

insert into public.work_orders (unit_id, lease_id, reported_by_tenant, source, category, priority, title, description, status, affects_health_safety, written_notice_at, vendor_name, vendor_phone, cost, resolved_at, created_at)
select
  l.unit_id, l.id, lt.tenant_id,
  w.source, w.category, w.priority, w.title, w.description, w.status,
  w.health_safety,
  -- A portal submission IS the tenant's written notice under §92.052.
  case when w.source = 'portal' then now() - ((w.notice_days_ago) || ' days')::interval end,
  case when w.status in ('asignada','en_progreso','esperando_refacciones','resuelta','cerrada') then w.vendor end,
  case when w.status in ('asignada','en_progreso','esperando_refacciones','resuelta','cerrada') then '(915) 555-' || lpad((3000 + w.rn * 17)::text, 4, '0') end,
  case when w.status in ('resuelta','cerrada') then w.cost end,
  case when w.status in ('resuelta','cerrada') then now() - (w.rn || ' days')::interval end,
  now() - ((w.notice_days_ago) || ' days')::interval
from (values
  -- rn, source, category, priority, title, description, status, health_safety, notice_days_ago, vendor, cost
  (1,  'portal'::wo_source, 'plomeria'::wo_category,   'urgente'::wo_priority, 'No hot water in the unit',            'The water heater stopped working four days ago. Only cold water.', 'en_progreso'::wo_status,          true,  11, 'Franklin Plumbing',   485.00),
  (2,  'portal',            'electricidad',            'urgente',              'Sparking outlet in the kitchen',      'The outlet by the sink sparked when I plugged in the kettle.',      'asignada',                        true,   4, 'Rio Grande Electric', 310.00),
  (3,  'portal',            'otro',                    'alta',                 'Air conditioning out — 104F outside', 'The AC has not cooled since Saturday. It is unbearable inside.',     'nueva',                           true,   2, 'Desert Air HVAC',     640.00),
  (4,  'whatsapp',          'electricidad',            'alta',                 'Bedroom outlets dead',                'No power to any outlet in the main bedroom.',                       'asignada',                        false,  6, 'Rio Grande Electric', 190.00),
  (5,  'telefono',          'cerrajeria',              'media',                'Front door lock sticking',            'The key goes in but will not turn.',                                'en_progreso',                     false,  9, 'Sun City Lock',       145.00),
  (6,  'personal',          'electrodomesticos',       'media',                'Dishwasher not draining',             'Standing water in the bottom after every cycle.',                    'esperando_refacciones',           false, 12, 'Appliance Pros',      220.00),
  (7,  'portal',            'limpieza',                'baja',                 'Common laundry room needs cleaning',  'Lint and detergent spills have built up.',                          'resuelta',                        false, 15, 'Clean Sweep EP',       95.00),
  (8,  'portal',            'plomeria',                'alta',                 'Kitchen sink backing up',             'Water comes back up when the disposal runs.',                        'cerrada',                         false, 18, 'Franklin Plumbing',   265.00),
  (9,  'whatsapp',          'electricidad',            'urgente',              'Breaker tripping repeatedly',         'The main breaker has tripped twice today.',                         'en_progreso',                     false,  3, 'Rio Grande Electric', 380.00),
  (10, 'telefono',          'otro',                    'baja',                 'Gate remote not working',             'The parking gate remote stopped responding.',                        'nueva',                           false,  5, 'Access Controls TX',  120.00),
  (11, 'personal',          'plomeria',                'media',                'Dripping shower head',                'Drips constantly even when fully closed.',                          'asignada',                        false, 21, 'Franklin Plumbing',    85.00),
  (12, 'portal',            'electrodomesticos',       'alta',                 'Stove burners will not light',        'Two of the four burners do not ignite.',                            'resuelta',                        false, 24, 'Appliance Pros',      175.00),
  (13, 'portal',            'cerrajeria',              'urgente',              'Front door will not latch',           'The deadbolt is loose and the door does not secure.',                'cerrada',                         false, 27, 'Sun City Lock',       210.00),
  (14, 'telefono',          'limpieza',                'baja',                 'Trash piling up by the dumpster',     'Bags left outside the enclosure again.',                            'resuelta',                        false, 30, 'Clean Sweep EP',       60.00),
  (15, 'personal',          'otro',                    'media',                'Damp patch spreading on wall',        'A damp stain on the living room wall is getting bigger.',            'esperando_refacciones',           false, 33, 'El Paso Restoration', 950.00)
) as w(rn, source, category, priority, title, description, status, health_safety, notice_days_ago, vendor, cost)
join lateral (
  select l.* from public.leases l
  where l.status = 'activo'
  order by l.created_at, l.id
  offset (w.rn - 1) limit 1
) l on true
join lateral (
  select lt.tenant_id from public.lease_tenants lt where lt.lease_id = l.id and lt.role = 'primary' limit 1
) lt on true;

insert into public.work_order_notes (work_order_id, body, is_internal)
select w.id, n.body, n.is_internal
from public.work_orders w
join lateral (values
  ('Vendor contacted, visit scheduled for tomorrow morning.', true),
  ('We have reached the vendor. The visit is scheduled for tomorrow between 9:00 and 12:00.', false)
) as n(body, is_internal) on true
where w.status <> 'nueva';

-- --------------------------------------------- a deposit clock, running
-- One terminated lease that has surrendered AND given a forwarding address,
-- so the "Deposits due" card and the compliance report both have a row.
-- Unit 31 by the same ordering the active leases used, so it does not
-- collide with them.

with target_unit as (
  select u.id, u.base_rent
  from public.units u join public.properties p on p.id = u.property_id
  where u.status = 'vacante'
  order by p.name, u.unit_number
  limit 1
),
ended as (
  insert into public.leases (
    unit_id, start_date, end_date, rent_amount, rent_due_day, grace_days,
    late_fee_type, late_fee_percent, late_fee_amount, deposit_amount, status,
    surrender_date, move_out_date, move_out_notes,
    forwarding_address, forwarding_address_received_at
  )
  select
    tu.id,
    (current_date - interval '14 months')::date,
    (current_date - interval '2 months')::date,
    tu.base_rent,
    1,
    2,
    'percent',
    10.00,
    0,
    tu.base_rent,
    'terminado',
    (current_date - interval '24 days')::date,
    (current_date - interval '24 days')::date,
    'Unit left clean. Carpet in the second bedroom is stained; keys and both remotes returned.',
    E'1200 Montana Ave, Apt 4\nEl Paso, TX 79902',
    (current_date - interval '18 days')::date
  from target_unit tu
  returning id
)
insert into public.lease_tenants (lease_id, tenant_id, role)
select ended.id, t.id, 'primary'
from ended
join lateral (
  select id from public.tenants order by created_at desc limit 1
) t on true;

-- ------------------------------------------------- two fresh move-ins
-- Added last, after the invoice run, because a tenant who took possession
-- this week genuinely has no invoice history yet. Their turnover checklists
-- are still in progress: one inside its 7-day rekey window, one already
-- past it, so both the amber and the red state of §92.156 are on screen.

with vacant as (
  select u.id, u.base_rent, row_number() over (order by p.name, u.unit_number) as rn
  from public.units u join public.properties p on p.id = u.property_id
  where u.status = 'vacante'
),
free_tenants as (
  select tn.id, row_number() over (order by tn.created_at, tn.id) as rn
  from public.tenants tn
  where not exists (select 1 from public.lease_tenants lt where lt.tenant_id = tn.id)
),
moved_in as (
  insert into public.leases (
    unit_id, start_date, end_date, rent_amount, rent_due_day, grace_days,
    late_fee_type, late_fee_percent, late_fee_amount, deposit_amount, status
  )
  select
    v.id,
    (current_date - d.days_ago)::date,
    (current_date - d.days_ago + interval '12 months' - interval '1 day')::date,
    v.base_rent, 1, 2, 'percent', 10.00, 0, v.base_rent, 'activo'
  from vacant v
  join (values (1, 4), (2, 9)) as d(rn, days_ago) on d.rn = v.rn
  returning id, unit_id, start_date
),
numbered_moves as (
  select m.*, row_number() over (order by m.start_date desc) as rn from moved_in m
),
tenanted as (
  insert into public.lease_tenants (lease_id, tenant_id, role)
  select nm.id, ft.id, 'primary'
  from numbered_moves nm join free_tenants ft on ft.rn = nm.rn
  returning lease_id
)
insert into public.unit_turnover_checklist (unit_id, lease_id, item, item_key, position, completed, completed_at)
select
  m.unit_id, m.id, c.item, c.item_key, c.position,
  -- The four-day-old move-in has made a start; the nine-day-old one has not,
  -- and its rekey is therefore two days past the statutory deadline.
  done.completed,
  case when done.completed then now() - interval '1 day' end
from numbered_moves m
cross join (values
  ('Rekey locks (required within 7 days)',          'rekey_locks',               0),
  ('Test smoke alarms',                             'test_smoke_alarms',         1),
  ('Verify deadbolt and keyless bolting device',    'verify_deadbolt_keyless',   2),
  ('Verify window latches',                         'verify_window_latches',     3),
  ('Document unit condition with photos',           'document_condition_photos', 4),
  ('Collect renters insurance certificate',         'collect_renters_insurance', 5)
) as c(item, item_key, position)
cross join lateral (
  select case
    when m.start_date > current_date - 7 then c.item_key in ('test_smoke_alarms', 'document_condition_photos')
    else false
  end as completed
) done;

update public.units u set status = 'ocupada'
where exists (select 1 from public.leases l where l.unit_id = u.id and l.status = 'activo');

-- ------------------------------------------- re-link the tenant logins
-- Deleting the old tenants cleared `profiles.tenant_id` (on delete set null),
-- so without this a tenant signs in successfully and lands on an empty
-- portal, because my_lease_ids() has nothing to match. Re-point each tenant
-- profile at the tenant record with the same email address.
--
-- Staff profiles are untouched: their tenant_id was already null and their
-- role carries the access.
update public.profiles p
set tenant_id = t.id
from auth.users u
join public.tenants t on lower(t.email) = lower(u.email)
where p.id = u.id
  and p.role = 'tenant'
  and p.tenant_id is distinct from t.id;

commit;
