/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalContractsRouteImport } from './routes/portal.contracts'
import { Route as PortalMaintenanceRouteImport } from './routes/portal.maintenance'
import { Route as PortalProfileRouteImport } from './routes/portal.profile'
import { Route as PortalReceiptsRouteImport } from './routes/portal.receipts'
import { Route as AppContractsIndexRouteImport } from './routes/app.contracts.index'
import { Route as AppContractsIdRouteImport } from './routes/app.contracts.$id'
import { Route as AppMaintenanceIndexRouteImport } from './routes/app.maintenance.index'
import { Route as AppMaintenanceIdRouteImport } from './routes/app.maintenance.$id'
import { Route as AppParkingIndexRouteImport } from './routes/app.parking.index'
import { Route as AppPaymentsIndexRouteImport } from './routes/app.payments.index'
import { Route as AppPropertiesIndexRouteImport } from './routes/app.properties.index'
import { Route as AppPropertiesIdRouteImport } from './routes/app.properties.$id'
import { Route as AppReceiptsIndexRouteImport } from './routes/app.receipts.index'
import { Route as AppReceiptsIdRouteImport } from './routes/app.receipts.$id'
import { Route as AppReportsIndexRouteImport } from './routes/app.reports.index'
import { Route as AppServicesIndexRouteImport } from './routes/app.services.index'
import { Route as AppSettingsIndexRouteImport } from './routes/app.settings.index'
import { Route as AppTenantsIndexRouteImport } from './routes/app.tenants.index'
import { Route as AppTenantsIdRouteImport } from './routes/app.tenants.$id'
import { Route as AppUnitsIndexRouteImport } from './routes/app.units.index'
import { Route as AppUnitsIdRouteImport } from './routes/app.units.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalContractsRoute = PortalContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMaintenanceRoute = PortalMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalReceiptsRoute = PortalReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => PortalRoute,
} as any)
const AppContractsIndexRoute = AppContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => AppRoute,
} as any)
const AppContractsIdRoute = AppContractsIdRouteImport.update({
  id: '/contracts/$id',
  path: '/contracts/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintenanceIndexRoute = AppMaintenanceIndexRouteImport.update({
  id: '/maintenance/',
  path: '/maintenance/',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintenanceIdRoute = AppMaintenanceIdRouteImport.update({
  id: '/maintenance/$id',
  path: '/maintenance/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppParkingIndexRoute = AppParkingIndexRouteImport.update({
  id: '/parking/',
  path: '/parking/',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsIndexRoute = AppPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesIndexRoute = AppPropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesIdRoute = AppPropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppReceiptsIndexRoute = AppReceiptsIndexRouteImport.update({
  id: '/receipts/',
  path: '/receipts/',
  getParentRoute: () => AppRoute,
} as any)
const AppReceiptsIdRoute = AppReceiptsIdRouteImport.update({
  id: '/receipts/$id',
  path: '/receipts/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesIndexRoute = AppServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsIndexRoute = AppTenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsIdRoute = AppTenantsIdRouteImport.update({
  id: '/tenants/$id',
  path: '/tenants/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppUnitsIndexRoute = AppUnitsIndexRouteImport.update({
  id: '/units/',
  path: '/units/',
  getParentRoute: () => AppRoute,
} as any)
const AppUnitsIdRoute = AppUnitsIdRouteImport.update({
  id: '/units/$id',
  path: '/units/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/portal/contracts': typeof PortalContractsRoute
  '/portal/maintenance': typeof PortalMaintenanceRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/receipts': typeof PortalReceiptsRoute
  '/app/': typeof AppIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/app/contracts/$id': typeof AppContractsIdRoute
  '/app/maintenance/$id': typeof AppMaintenanceIdRoute
  '/app/properties/$id': typeof AppPropertiesIdRoute
  '/app/receipts/$id': typeof AppReceiptsIdRoute
  '/app/tenants/$id': typeof AppTenantsIdRoute
  '/app/units/$id': typeof AppUnitsIdRoute
  '/app/contracts/': typeof AppContractsIndexRoute
  '/app/maintenance/': typeof AppMaintenanceIndexRoute
  '/app/parking/': typeof AppParkingIndexRoute
  '/app/payments/': typeof AppPaymentsIndexRoute
  '/app/properties/': typeof AppPropertiesIndexRoute
  '/app/receipts/': typeof AppReceiptsIndexRoute
  '/app/reports/': typeof AppReportsIndexRoute
  '/app/services/': typeof AppServicesIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/tenants/': typeof AppTenantsIndexRoute
  '/app/units/': typeof AppUnitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/portal/contracts': typeof PortalContractsRoute
  '/portal/maintenance': typeof PortalMaintenanceRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/receipts': typeof PortalReceiptsRoute
  '/app': typeof AppIndexRoute
  '/portal': typeof PortalIndexRoute
  '/app/contracts/$id': typeof AppContractsIdRoute
  '/app/maintenance/$id': typeof AppMaintenanceIdRoute
  '/app/properties/$id': typeof AppPropertiesIdRoute
  '/app/receipts/$id': typeof AppReceiptsIdRoute
  '/app/tenants/$id': typeof AppTenantsIdRoute
  '/app/units/$id': typeof AppUnitsIdRoute
  '/app/contracts': typeof AppContractsIndexRoute
  '/app/maintenance': typeof AppMaintenanceIndexRoute
  '/app/parking': typeof AppParkingIndexRoute
  '/app/payments': typeof AppPaymentsIndexRoute
  '/app/properties': typeof AppPropertiesIndexRoute
  '/app/receipts': typeof AppReceiptsIndexRoute
  '/app/reports': typeof AppReportsIndexRoute
  '/app/services': typeof AppServicesIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/tenants': typeof AppTenantsIndexRoute
  '/app/units': typeof AppUnitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/portal/contracts': typeof PortalContractsRoute
  '/portal/maintenance': typeof PortalMaintenanceRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/receipts': typeof PortalReceiptsRoute
  '/app/': typeof AppIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/app/contracts/$id': typeof AppContractsIdRoute
  '/app/maintenance/$id': typeof AppMaintenanceIdRoute
  '/app/properties/$id': typeof AppPropertiesIdRoute
  '/app/receipts/$id': typeof AppReceiptsIdRoute
  '/app/tenants/$id': typeof AppTenantsIdRoute
  '/app/units/$id': typeof AppUnitsIdRoute
  '/app/contracts/': typeof AppContractsIndexRoute
  '/app/maintenance/': typeof AppMaintenanceIndexRoute
  '/app/parking/': typeof AppParkingIndexRoute
  '/app/payments/': typeof AppPaymentsIndexRoute
  '/app/properties/': typeof AppPropertiesIndexRoute
  '/app/receipts/': typeof AppReceiptsIndexRoute
  '/app/reports/': typeof AppReportsIndexRoute
  '/app/services/': typeof AppServicesIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/tenants/': typeof AppTenantsIndexRoute
  '/app/units/': typeof AppUnitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/portal'
    | '/reset-password'
    | '/portal/contracts'
    | '/portal/maintenance'
    | '/portal/profile'
    | '/portal/receipts'
    | '/app/'
    | '/portal/'
    | '/app/contracts/$id'
    | '/app/maintenance/$id'
    | '/app/properties/$id'
    | '/app/receipts/$id'
    | '/app/tenants/$id'
    | '/app/units/$id'
    | '/app/contracts/'
    | '/app/maintenance/'
    | '/app/parking/'
    | '/app/payments/'
    | '/app/properties/'
    | '/app/receipts/'
    | '/app/reports/'
    | '/app/services/'
    | '/app/settings/'
    | '/app/tenants/'
    | '/app/units/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/portal/contracts'
    | '/portal/maintenance'
    | '/portal/profile'
    | '/portal/receipts'
    | '/app'
    | '/portal'
    | '/app/contracts/$id'
    | '/app/maintenance/$id'
    | '/app/properties/$id'
    | '/app/receipts/$id'
    | '/app/tenants/$id'
    | '/app/units/$id'
    | '/app/contracts'
    | '/app/maintenance'
    | '/app/parking'
    | '/app/payments'
    | '/app/properties'
    | '/app/receipts'
    | '/app/reports'
    | '/app/services'
    | '/app/settings'
    | '/app/tenants'
    | '/app/units'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/portal'
    | '/reset-password'
    | '/portal/contracts'
    | '/portal/maintenance'
    | '/portal/profile'
    | '/portal/receipts'
    | '/app/'
    | '/portal/'
    | '/app/contracts/$id'
    | '/app/maintenance/$id'
    | '/app/properties/$id'
    | '/app/receipts/$id'
    | '/app/tenants/$id'
    | '/app/units/$id'
    | '/app/contracts/'
    | '/app/maintenance/'
    | '/app/parking/'
    | '/app/payments/'
    | '/app/properties/'
    | '/app/receipts/'
    | '/app/reports/'
    | '/app/services/'
    | '/app/settings/'
    | '/app/tenants/'
    | '/app/units/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/contracts': {
      id: '/portal/contracts'
      path: '/contracts'
      fullPath: '/portal/contracts'
      preLoaderRoute: typeof PortalContractsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/maintenance': {
      id: '/portal/maintenance'
      path: '/maintenance'
      fullPath: '/portal/maintenance'
      preLoaderRoute: typeof PortalMaintenanceRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/receipts': {
      id: '/portal/receipts'
      path: '/receipts'
      fullPath: '/portal/receipts'
      preLoaderRoute: typeof PortalReceiptsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/app/contracts/': {
      id: '/app/contracts/'
      path: '/contracts'
      fullPath: '/app/contracts/'
      preLoaderRoute: typeof AppContractsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contracts/$id': {
      id: '/app/contracts/$id'
      path: '/contracts/$id'
      fullPath: '/app/contracts/$id'
      preLoaderRoute: typeof AppContractsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/maintenance/': {
      id: '/app/maintenance/'
      path: '/maintenance'
      fullPath: '/app/maintenance/'
      preLoaderRoute: typeof AppMaintenanceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/maintenance/$id': {
      id: '/app/maintenance/$id'
      path: '/maintenance/$id'
      fullPath: '/app/maintenance/$id'
      preLoaderRoute: typeof AppMaintenanceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/parking/': {
      id: '/app/parking/'
      path: '/parking'
      fullPath: '/app/parking/'
      preLoaderRoute: typeof AppParkingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments/': {
      id: '/app/payments/'
      path: '/payments'
      fullPath: '/app/payments/'
      preLoaderRoute: typeof AppPaymentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/properties/': {
      id: '/app/properties/'
      path: '/properties'
      fullPath: '/app/properties/'
      preLoaderRoute: typeof AppPropertiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/properties/$id': {
      id: '/app/properties/$id'
      path: '/properties/$id'
      fullPath: '/app/properties/$id'
      preLoaderRoute: typeof AppPropertiesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/receipts/': {
      id: '/app/receipts/'
      path: '/receipts'
      fullPath: '/app/receipts/'
      preLoaderRoute: typeof AppReceiptsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/receipts/$id': {
      id: '/app/receipts/$id'
      path: '/receipts/$id'
      fullPath: '/app/receipts/$id'
      preLoaderRoute: typeof AppReceiptsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports/': {
      id: '/app/reports/'
      path: '/reports'
      fullPath: '/app/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/services/': {
      id: '/app/services/'
      path: '/services'
      fullPath: '/app/services/'
      preLoaderRoute: typeof AppServicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tenants/': {
      id: '/app/tenants/'
      path: '/tenants'
      fullPath: '/app/tenants/'
      preLoaderRoute: typeof AppTenantsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tenants/$id': {
      id: '/app/tenants/$id'
      path: '/tenants/$id'
      fullPath: '/app/tenants/$id'
      preLoaderRoute: typeof AppTenantsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/units/': {
      id: '/app/units/'
      path: '/units'
      fullPath: '/app/units/'
      preLoaderRoute: typeof AppUnitsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/units/$id': {
      id: '/app/units/$id'
      path: '/units/$id'
      fullPath: '/app/units/$id'
      preLoaderRoute: typeof AppUnitsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppContractsIdRoute: typeof AppContractsIdRoute
  AppMaintenanceIdRoute: typeof AppMaintenanceIdRoute
  AppPropertiesIdRoute: typeof AppPropertiesIdRoute
  AppReceiptsIdRoute: typeof AppReceiptsIdRoute
  AppTenantsIdRoute: typeof AppTenantsIdRoute
  AppUnitsIdRoute: typeof AppUnitsIdRoute
  AppContractsIndexRoute: typeof AppContractsIndexRoute
  AppMaintenanceIndexRoute: typeof AppMaintenanceIndexRoute
  AppParkingIndexRoute: typeof AppParkingIndexRoute
  AppPaymentsIndexRoute: typeof AppPaymentsIndexRoute
  AppPropertiesIndexRoute: typeof AppPropertiesIndexRoute
  AppReceiptsIndexRoute: typeof AppReceiptsIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppServicesIndexRoute: typeof AppServicesIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppTenantsIndexRoute: typeof AppTenantsIndexRoute
  AppUnitsIndexRoute: typeof AppUnitsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppContractsIdRoute: AppContractsIdRoute,
  AppMaintenanceIdRoute: AppMaintenanceIdRoute,
  AppPropertiesIdRoute: AppPropertiesIdRoute,
  AppReceiptsIdRoute: AppReceiptsIdRoute,
  AppTenantsIdRoute: AppTenantsIdRoute,
  AppUnitsIdRoute: AppUnitsIdRoute,
  AppContractsIndexRoute: AppContractsIndexRoute,
  AppMaintenanceIndexRoute: AppMaintenanceIndexRoute,
  AppParkingIndexRoute: AppParkingIndexRoute,
  AppPaymentsIndexRoute: AppPaymentsIndexRoute,
  AppPropertiesIndexRoute: AppPropertiesIndexRoute,
  AppReceiptsIndexRoute: AppReceiptsIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppServicesIndexRoute: AppServicesIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppTenantsIndexRoute: AppTenantsIndexRoute,
  AppUnitsIndexRoute: AppUnitsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PortalRouteChildren {
  PortalContractsRoute: typeof PortalContractsRoute
  PortalMaintenanceRoute: typeof PortalMaintenanceRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalReceiptsRoute: typeof PortalReceiptsRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalContractsRoute: PortalContractsRoute,
  PortalMaintenanceRoute: PortalMaintenanceRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalReceiptsRoute: PortalReceiptsRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
