/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppContractsRouteImport } from './routes/app.contracts'
import { Route as AppMaintenanceRouteImport } from './routes/app.maintenance'
import { Route as AppParkingRouteImport } from './routes/app.parking'
import { Route as AppPaymentsRouteImport } from './routes/app.payments'
import { Route as AppPropertiesRouteImport } from './routes/app.properties'
import { Route as AppReceiptsRouteImport } from './routes/app.receipts'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppServicesRouteImport } from './routes/app.services'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppTenantsRouteImport } from './routes/app.tenants'
import { Route as AppUnitsRouteImport } from './routes/app.units'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalContractsRouteImport } from './routes/portal.contracts'
import { Route as PortalMaintenanceRouteImport } from './routes/portal.maintenance'
import { Route as PortalProfileRouteImport } from './routes/portal.profile'
import { Route as PortalReceiptsRouteImport } from './routes/portal.receipts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppContractsRoute = AppContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintenanceRoute = AppMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AppRoute,
} as any)
const AppParkingRoute = AppParkingRouteImport.update({
  id: '/parking',
  path: '/parking',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesRoute = AppPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AppRoute,
} as any)
const AppReceiptsRoute = AppReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsRoute = AppTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AppRoute,
} as any)
const AppUnitsRoute = AppUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AppRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalContractsRoute = PortalContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMaintenanceRoute = PortalMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalReceiptsRoute = PortalReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/app/contracts': typeof AppContractsRoute
  '/app/maintenance': typeof AppMaintenanceRoute
  '/app/parking': typeof AppParkingRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/properties': typeof AppPropertiesRoute
  '/app/receipts': typeof AppReceiptsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/services': typeof AppServicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tenants': typeof AppTenantsRoute
  '/app/units': typeof AppUnitsRoute
  '/portal/contracts': typeof PortalContractsRoute
  '/portal/maintenance': typeof PortalMaintenanceRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/receipts': typeof PortalReceiptsRoute
  '/app/': typeof AppIndexRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/contracts': typeof AppContractsRoute
  '/app/maintenance': typeof AppMaintenanceRoute
  '/app/parking': typeof AppParkingRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/properties': typeof AppPropertiesRoute
  '/app/receipts': typeof AppReceiptsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/services': typeof AppServicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tenants': typeof AppTenantsRoute
  '/app/units': typeof AppUnitsRoute
  '/portal/contracts': typeof PortalContractsRoute
  '/portal/maintenance': typeof PortalMaintenanceRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/receipts': typeof PortalReceiptsRoute
  '/app': typeof AppIndexRoute
  '/portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/app/contracts': typeof AppContractsRoute
  '/app/maintenance': typeof AppMaintenanceRoute
  '/app/parking': typeof AppParkingRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/properties': typeof AppPropertiesRoute
  '/app/receipts': typeof AppReceiptsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/services': typeof AppServicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tenants': typeof AppTenantsRoute
  '/app/units': typeof AppUnitsRoute
  '/portal/contracts': typeof PortalContractsRoute
  '/portal/maintenance': typeof PortalMaintenanceRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/receipts': typeof PortalReceiptsRoute
  '/app/': typeof AppIndexRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/portal'
    | '/app/contracts'
    | '/app/maintenance'
    | '/app/parking'
    | '/app/payments'
    | '/app/properties'
    | '/app/receipts'
    | '/app/reports'
    | '/app/services'
    | '/app/settings'
    | '/app/tenants'
    | '/app/units'
    | '/portal/contracts'
    | '/portal/maintenance'
    | '/portal/profile'
    | '/portal/receipts'
    | '/app/'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/contracts'
    | '/app/maintenance'
    | '/app/parking'
    | '/app/payments'
    | '/app/properties'
    | '/app/receipts'
    | '/app/reports'
    | '/app/services'
    | '/app/settings'
    | '/app/tenants'
    | '/app/units'
    | '/portal/contracts'
    | '/portal/maintenance'
    | '/portal/profile'
    | '/portal/receipts'
    | '/app'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/portal'
    | '/app/contracts'
    | '/app/maintenance'
    | '/app/parking'
    | '/app/payments'
    | '/app/properties'
    | '/app/receipts'
    | '/app/reports'
    | '/app/services'
    | '/app/settings'
    | '/app/tenants'
    | '/app/units'
    | '/portal/contracts'
    | '/portal/maintenance'
    | '/portal/profile'
    | '/portal/receipts'
    | '/app/'
    | '/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contracts': {
      id: '/app/contracts'
      path: '/contracts'
      fullPath: '/app/contracts'
      preLoaderRoute: typeof AppContractsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/maintenance': {
      id: '/app/maintenance'
      path: '/maintenance'
      fullPath: '/app/maintenance'
      preLoaderRoute: typeof AppMaintenanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/parking': {
      id: '/app/parking'
      path: '/parking'
      fullPath: '/app/parking'
      preLoaderRoute: typeof AppParkingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/properties': {
      id: '/app/properties'
      path: '/properties'
      fullPath: '/app/properties'
      preLoaderRoute: typeof AppPropertiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/receipts': {
      id: '/app/receipts'
      path: '/receipts'
      fullPath: '/app/receipts'
      preLoaderRoute: typeof AppReceiptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/services': {
      id: '/app/services'
      path: '/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tenants': {
      id: '/app/tenants'
      path: '/tenants'
      fullPath: '/app/tenants'
      preLoaderRoute: typeof AppTenantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/units': {
      id: '/app/units'
      path: '/units'
      fullPath: '/app/units'
      preLoaderRoute: typeof AppUnitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/contracts': {
      id: '/portal/contracts'
      path: '/contracts'
      fullPath: '/portal/contracts'
      preLoaderRoute: typeof PortalContractsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/maintenance': {
      id: '/portal/maintenance'
      path: '/maintenance'
      fullPath: '/portal/maintenance'
      preLoaderRoute: typeof PortalMaintenanceRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/receipts': {
      id: '/portal/receipts'
      path: '/receipts'
      fullPath: '/portal/receipts'
      preLoaderRoute: typeof PortalReceiptsRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface AppRouteChildren {
  AppContractsRoute: typeof AppContractsRoute
  AppMaintenanceRoute: typeof AppMaintenanceRoute
  AppParkingRoute: typeof AppParkingRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppPropertiesRoute: typeof AppPropertiesRoute
  AppReceiptsRoute: typeof AppReceiptsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppServicesRoute: typeof AppServicesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTenantsRoute: typeof AppTenantsRoute
  AppUnitsRoute: typeof AppUnitsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppContractsRoute: AppContractsRoute,
  AppMaintenanceRoute: AppMaintenanceRoute,
  AppParkingRoute: AppParkingRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppPropertiesRoute: AppPropertiesRoute,
  AppReceiptsRoute: AppReceiptsRoute,
  AppReportsRoute: AppReportsRoute,
  AppServicesRoute: AppServicesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTenantsRoute: AppTenantsRoute,
  AppUnitsRoute: AppUnitsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PortalRouteChildren {
  PortalContractsRoute: typeof PortalContractsRoute
  PortalMaintenanceRoute: typeof PortalMaintenanceRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalReceiptsRoute: typeof PortalReceiptsRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalContractsRoute: PortalContractsRoute,
  PortalMaintenanceRoute: PortalMaintenanceRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalReceiptsRoute: PortalReceiptsRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
